# Generated by Django 4.2.6 on 2023-12-22 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Enter an address', verbose_name='Address')),
                ('workload', test_django.models.IntegerRangeField(help_text='Choose an workload', verbose_name='Workload(0 - none, 10 - full)')),
                ('rating', test_django.models.IntegerRangeField(help_text='Choose a rating', verbose_name='Rating(0 - puke, 10 - super)')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a message title', max_length=50, verbose_name='Message title')),
                ('body', models.CharField(help_text='Enter a message body', max_length=150, verbose_name='Message body')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a first name', max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(help_text='Enter a surname', max_length=50, verbose_name='Surname')),
                ('experience', test_django.models.IntegerRangeField(help_text='Choose an experience', verbose_name='Experience')),
                ('rating', test_django.models.IntegerRangeField(help_text='Choose a rating', verbose_name='Rating(0 - puke, 10 - super)')),
                ('department', models.ForeignKey(help_text='Choose a department', on_delete=django.db.models.deletion.CASCADE, to='test_django.department', verbose_name='Department')),
                ('id_user', models.ForeignKey(blank=True, help_text='Choose an id user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id User')),
            ],
            options={
                'db_table': 'Mechanic',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a first name', max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(help_text='Enter a surname', max_length=50, verbose_name='Surname')),
                ('phone_number', models.CharField(help_text='Enter a phone number', max_length=20, verbose_name='Phone Number')),
                ('city', models.CharField(default='Moscow', help_text='Enter a city', max_length=50, verbose_name='City')),
                ('id_user', models.ForeignKey(blank=True, help_text='Choose an id user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id User')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=50, verbose_name='Name')),
                ('mileage', models.IntegerField(help_text='Enter a mileage', verbose_name='Mileage')),
                ('malfunction', models.TextField(help_text='Enter a malfunction', verbose_name='Malfunction')),
                ('isAccepted', models.BooleanField(default=False)),
                ('repairIsDone', models.BooleanField(default=False)),
                ('client', models.ForeignKey(help_text='Choose a client', on_delete=django.db.models.deletion.CASCADE, to='test_django.client', verbose_name='Client')),
                ('mechanics', models.ManyToManyField(help_text='Choose a mechanic(s)', null=True, to='test_django.mechanic', verbose_name='Mechanic(s)')),
                ('message', models.ForeignKey(help_text='Choose a message', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.message', verbose_name='Message')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
    ]
