# Generated by Django 4.2.6 on 2023-12-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0003_message_main_mech'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
